values:
    ### Enviroment Settings
    environment: ec2_environment
    ### Project Settings
    cluster_name: ec2-teste
    owner: group:default/admin
    instance_type: t3.medium
    volume_size: 30
    keypair_name: platform_kp
    ### Network Settings
    vpc_id: vpc-03390e24728683217
    domain: ec2.enviroment.platform.vee.codes
    hostedZoneId: Z0588229N2Y5ZB0SPHUM
    subnet_id: subnet-02b0767acee0b65bb
    ### Ingress Settings
    ingress_window: false
    ingress_type: 
    kong_mode: 
    external_db: 
    basic_auth: 
    certmanager_window: 
    issuer_type: 
    email: 
    ### Terraform Backend Settings
    terraformStateBucketName: veecode-apr-terraform-state
    terraformStateBucketRegion: us-east-1
    infracost: true
    ### Publish Settings
    host: github.com
    destination: veecode-apr/ec2-teste
    specPublish: ${{ parameters.specPublish | parseRepoUrl | pick('owner') }}/${{ parameters.specPublish | parseRepoUrl | pick('repo') }}
    specPublishRepo: ${{ parameters.specPublish | parseRepoUrl | pick('repo') }}
    specPublishBranch: 
    ### Observability Settings
    observability_window: true
    observability_grafana_url: https://grafana.apr.vee.codes